# Generated by Django 5.0.6 on 2024-06-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dp_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profileimage',
        ),
    ]
